security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                failure_path: /reject
            logout:
                path: /logout
                target: /

    access_control:
            # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        #Activation role admin, ne marche pas encore
        #- { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
