security:
    providers:
        in_memory:
            memory:
                users:
                    profil: { password: profil, roles: 'ROLE_PROFILE' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true
            http_basic: true
        profile:
            pattern: ^/profile
            anonymous: true
            http_basic: true
        main:
            anonymous: true

    access_control:

        - { path: ^/profile, roles: ROLE_PROFILE }
        - { path: ^/admin, roles: ROLE_ADMIN }


