parameters:
    app.path.game_images: web/uploads/images/game
    app.path.post_images: web/uploads/images/post
    app.path.team_images: web/uploads/images/team
    app.path.user_images: web/uploads/images/user

vich_uploader:
    db_driver: orm

    mappings:
        game_images:
            uri_prefix: '%app.path.game_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/game'

        post_images:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/post'

        team_images:
            uri_prefix: '%app.path.team_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/team'

        user_images:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/user'