parameters:
    app.path.game_images: /uploads/images/game
    app.path.post_images: /uploads/images/post
    app.path.team_images: /uploads/images/team
    app.path.user_images: /uploads/images/user

vich_uploader:
    db_driver: orm

    mappings:
        Game:
            uri_prefix: '%app.path.game_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/game'

        Post:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/post'

        Team:
            uri_prefix: '%app.path.team_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/team'

        User:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/user'
